### ISSUE TITLE
对应的属性面板的template是否能一起上传

### ISSUE THREAD

**Issue by tzraeq** [gongxufan/web-topology#1]
或者说能否提供一个简单的模版，应该怎样编写？

**Comment by zero-edge-code** [comment]
其实属性面板的模板编辑很简单的,直接把模板页面写在一个单独的html中,然后通过easyui的accordion加载.

因为是一个项目,设计到数据库和UI的设计，在这里就不方便上传了，而且剥离也挺麻烦。

**Comment by ZhaoWei9527** [comment]
能不能简单的做个示例？不知道怎么对应起图上的那些东西。
