### ISSUE TITLE
添加直线（不限于直线）时候会报js错误

### ISSUE THREAD

**Issue by illusion612** [gongxufan/web-topology#2]
![image](https://user-images.githubusercontent.com/54100148/63007541-684fe280-beb3-11e9-9c51-9caf3222c065.png)

                    this.add(l);
                    this.add(m);
                    self.beginNode = null;
                    this.remove(self.link);
                    self.link = null;

画终点节点时候找不到对象m

**Comment by zero-edge-code** [comment]
这的确是个问题，https://github.com/gongxufan/web-topology/commit/142a21d39699ab74c1a68e40f343cba51288e211

**Comment by illusion612** [comment]
> 这的确是个问题，[142a21d](https://github.com/gongxufan/web-topology/commit/142a21d39699ab74c1a68e40f343cba51288e211)

![image](https://user-images.githubusercontent.com/54100148/63921399-50f92380-ca75-11e9-841d-792f152b0b15.png)

这里还是不对吧    没这个变量

**Comment by zero-edge-code** [comment]
嗯，这行代码可以去掉的

**Comment by illusion612** [comment]
发现一个貌似是jtopo的bug，可能对topo编辑器有影响，弄了半天没搞定，你看看有没有兴趣


描述：
放大整个舞台后，动态添加“容器”会无法显示，并可以重复添加，缩小到一定程度（应该是1.0）会显示出来；（可以看附件的操作视频）
缩小后再放大到原来的倍数，可以显示，保存到后台再读取也可以出现，如果是直接在放大情况下添加一个容器（不显示，但是实际存在），保存后是不显示的；


GitHub这个地址无法带附件，，视频放在蓝奏云了


蓝奏云下载链接：https://www.lanzous.com/i6mxfab








------------------ 原始邮件 ------------------
发件人:&nbsp;"潇湘往事"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月10日(星期二) 下午4:10
收件人:&nbsp;"gongxufan/web-topology"<web-topology@noreply.github.com&gt;;
抄送:&nbsp;"树欲静而风不止"<1099062139@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gongxufan/web-topology] 添加直线（不限于直线）时候会报js错误 (#2)




嗯，这行代码可以去掉的

**Comment by zero-edge-code** [comment]
> 放大整个舞台后

休息了一个月，我现在是通过选中多个节点后，右键新建分组，没有出现你描述的问题哦。

**Comment by illusion612** [comment]
不知道您有没有看附件的操作视频（https://www.lanzous.com/i6mxfab）


https://gongxufan.github.io/web-topology/topologyEditor.html&nbsp;&nbsp;
是在这个地址上操作的，chrome和IE必现，是要先放到很大，再添加容器








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"潇湘往事"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 上午9:33
收件人:&nbsp;"gongxufan/web-topology"<web-topology@noreply.github.com&gt;;
抄送:&nbsp;"树欲静而风不止"<1099062139@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gongxufan/web-topology] 添加直线（不限于直线）时候会报js错误 (#2)



 
放大整个舞台后
  
休息了一个月，我现在是通过选中多个节点后，右键新建分组，没有出现你描述的问题哦。
